[package]
name = "monitro"
version = "0.1.0"
edition = "2021"

[dependencies]

[dependencies.windows]
version = "0.32.0"
features = [
    "Win32_Foundation",
    "Win32_Devices_Display",
    "Win32_Graphics_Gdi",
    "Win32_UI_Shell",
    "Win32_System_Com",
    "Win32_System_Ole",
]
